name: MacOS Build v1

on: [push, pull_request, workflow_dispatch]
concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: 'macos-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pyenv
        shell: bash
        run: |
          brew update
          brew install pyenv

      - name: Update shell
        shell: bash
        run: |
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
          echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
          echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
          echo "alias brew='env PATH=\"\${PATH//\$(pyenv root)\/shims:/}\" brew'" >> ~/.bash_profile
          tail ~/.bash_profile

      - name: Install python
        shell: bash
        run: |
          source ~/.bash_profile
          env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.9.4
          pyenv global 3.9.4

